/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-01-16 09:15:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.companyReview;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class companyDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1704699206728L));
    _jspx_dependants.put("jar:file:/D:/Algo/Algo/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>알바는 알고하자 - 알고</title>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common.css\">  \r\n");
      out.write("	<script type=\"text/javascript\" src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"//code.jquery.com/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- css 추가 -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/companyReview/company_detail.css\">  \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<!-- 헤더 -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- 내용 넣기 -->\r\n");
      out.write("	<main>\r\n");
      out.write("		<!-- 1. 기업리뷰 배너-->\r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"banner-navi\"> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">홈</a> &nbsp;&nbsp; &gt; &nbsp;&nbsp; <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/companyReview/\">기업리뷰</a></div>\r\n");
      out.write("            <div class=\"banner\">\r\n");
      out.write("                <div class=\"banner-txt\">\r\n");
      out.write("                    <h1>기업 리뷰</h1>\r\n");
      out.write("                    <p><span>알바는 알고하자!</span> 아르바이트 관련 기업들에 대한 후기를 보는 공간</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <img src=\"https://i.ibb.co/Ch8wrSg/building-banner.png\" width=\"107px\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <!-- 2. 메인 평점 -->\r\n");
      out.write("        <section id=\"co-section-2\">\r\n");
      out.write("            <div class=\"co-main-box\">\r\n");
      out.write("                <h3>한진 택배</h3>\r\n");
      out.write("                <button onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/companyReview/write'\">리뷰 작성</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"co-main-re-box\">\r\n");
      out.write("                <div class=\"co-main-re-1\">\r\n");
      out.write("                    <span class=\"co-main-re-1-txt\">알바 리뷰 평점</span> (<span>10명</span>)\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <div class=\"star_point\">4.8</div>\r\n");
      out.write("                        <div class =\"star_rating\" id=\"starRate1\">\r\n");
      out.write("                            <span class=\"star on\" value=\"1\"> </span>\r\n");
      out.write("                            <span class=\"star on\" value=\"2\"> </span>\r\n");
      out.write("                            <span class=\"star on\" value=\"3\"> </span>\r\n");
      out.write("                            <span class=\"star on\" value=\"4\"> </span>\r\n");
      out.write("                            <span class=\"star on\" value=\"5\"> </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <table class=\"co-main-re-2\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>위치</th>\r\n");
      out.write("                        <td>서울특별시 중구 남대문로 63</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>업계</th>\r\n");
      out.write("                        <td>운송</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>동일업계순위</th>\r\n");
      out.write("                        <td>4위</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>홈페이지</th>\r\n");
      out.write("                        <td>https://www.hanjin.com</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("                <div class=\"co-main-re-3\">\r\n");
      out.write("                    BEST 알고 한줄평\r\n");
      out.write("                    <div class=\"review-word-box\">\r\n");
      out.write("                        연소자의 근로는 특별한 보호를 받는다. 제2항의 재판관중 3인은 국회에서 선출하는 자를, 3인은 대법원장이 지명하는 자를 임명한다.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <!-- 3. 디테일 평점 -->\r\n");
      out.write("        <section class=\"co-main-re-box2\">\r\n");
      out.write("            <div class=\"co-sub-re-1\">\r\n");
      out.write("                평가\r\n");
      out.write("                <div class=\"sub-rate\" style=\"margin-top:25px;\">\r\n");
      out.write("                    <div class=\"sub-rate-txt\">일과 삶의 균형</div>\r\n");
      out.write("                    <div class =\"star_rating\" id=\"starRate2\">\r\n");
      out.write("                        <span class=\"star on\" value=\"1\"> </span>\r\n");
      out.write("                        <span class=\"star on\" value=\"2\"> </span>\r\n");
      out.write("                        <span class=\"star on\" value=\"3\"> </span>\r\n");
      out.write("                        <span class=\"star on\" value=\"4\"> </span>\r\n");
      out.write("                        <span class=\"star on\" value=\"5\"> </span>\r\n");
      out.write("                        <div class=\"sub_star_point\">평점 4.2</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sub-rate\">\r\n");
      out.write("                    <div class=\"sub-rate-txt\">급여 및 복지</div>\r\n");
      out.write("                    <div class =\"star_rating\" id=\"starRate3\">\r\n");
      out.write("                        <span class=\"star on\" value=\"1\"> </span>\r\n");
      out.write("                        <span class=\"star on\" value=\"2\"> </span>\r\n");
      out.write("                        <span class=\"star on\" value=\"3\"> </span>\r\n");
      out.write("                        <span class=\"star on\" value=\"4\"> </span>\r\n");
      out.write("                        <span class=\"star on\" value=\"5\"> </span>\r\n");
      out.write("                        <div class=\"sub_star_point\">평점 4.5</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sub-rate\">\r\n");
      out.write("                    <div class=\"sub-rate-txt\">근무 분위기</div>\r\n");
      out.write("                    <div class =\"star_rating\" id=\"starRate4\">\r\n");
      out.write("                        <span class=\"star on\" value=\"1\"> </span>\r\n");
      out.write("                        <span class=\"star on\" value=\"2\"> </span>\r\n");
      out.write("                        <span class=\"star on\" value=\"3\"> </span>\r\n");
      out.write("                        <span class=\"star on\" value=\"4\"> </span>\r\n");
      out.write("                        <span class=\"star\" value=\"5\"> </span>\r\n");
      out.write("                        <div class=\"sub_star_point\">평점 3.8</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sub-rate\">\r\n");
      out.write("                    <div class=\"sub-rate-txt\">재취업 의사</div>\r\n");
      out.write("                    <div class =\"star_rating\" id=\"starRate4\">\r\n");
      out.write("                        <span class=\"star on\" value=\"1\"> </span>\r\n");
      out.write("                        <span class=\"star on\" value=\"2\"> </span>\r\n");
      out.write("                        <span class=\"star on\" value=\"3\"> </span>\r\n");
      out.write("                        <span class=\"star on\" value=\"4\"> </span>\r\n");
      out.write("                        <span class=\"star on\" value=\"5\"> </span>\r\n");
      out.write("                        <div class=\"sub_star_point\">평점 4.0</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"co-sub-re-2\">\r\n");
      out.write("                한줄 리뷰\r\n");
      out.write("                <div class=\"review-word-box\">\r\n");
      out.write("                    연소자의 근로는 특별한 보호를 받는다. 제2항의 재판관중 3인은 국회에서 선출하는 자를, 3인은 대법원장이 지명하는 자를 임명한다.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"review-word-box\">\r\n");
      out.write("                    연소자의 근로는 특별한 보호를 받는다. 제2항의 재판관중 3인은 국회에서 선출하는 자를, 3인은 대법원장이 지명하는 자를 임명한다.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"review-word-box\">\r\n");
      out.write("                    연소자의 근로는 특별한 보호를 받는다. 제2항의 재판관중 3인은 국회에서 선출하는 자를, 3인은 대법원장이 지명하는 자를 임명한다.\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"pagging\">\r\n");
      out.write("                <div class=\"prev_page\" id=\"prev_page\">&lt;</div>\r\n");
      out.write("                <div class=\"pages\">\r\n");
      out.write("                    <span class=\"active\">1</span>\r\n");
      out.write("                    <span>2</span>\r\n");
      out.write("                    <span>3</span>\r\n");
      out.write("                    <span>4</span>\r\n");
      out.write("                    <span>5</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"next_page\" id=\"next_page\">&gt;</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <div style=\"width:104px; margin:30px auto;\">\r\n");
      out.write("            <button class=\"com-re-de-bu\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/companyReview/list'\">목록</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("	\r\n");
      out.write("    <!-- 푸터 -->\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/footer.jsp", out, false);
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("	<!--js 추가-->\r\n");
      out.write("	<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/top.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /views/companyReview/companyDetail.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /views/companyReview/companyDetail.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/views/companyReview/companyDetail.jsp(4,0) '${ pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
