/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-01-16 07:59:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.company_005freview;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1704699206728L));
    _jspx_dependants.put("jar:file:/D:/Algo/Algo/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>알바는 알고하자 - 알고</title>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common.css\">  \r\n");
      out.write("	<script type=\"text/javascript\" src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"//code.jquery.com/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- css 추가 -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/company_review/index.css\">  \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<!-- 헤더 -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- 내용 넣기 -->\r\n");
      out.write("	<main>\r\n");
      out.write("		<!-- 1. 기업리뷰 배너-->\r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"banner-navi\"> <a href=\"../index.html\">홈</a> &nbsp;&nbsp; &gt; &nbsp;&nbsp; <a href=\"./index.html\">기업리뷰</a></div>\r\n");
      out.write("            <div class=\"banner\">\r\n");
      out.write("                <div class=\"banner-txt\">\r\n");
      out.write("                    <h1>기업 리뷰</h1>\r\n");
      out.write("                    <p><span>알바는 알고하자!</span> 아르바이트 관련 기업들에 대한 후기를 보는 공간</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <img src=\"https://i.ibb.co/Ch8wrSg/building-banner.png\" width=\"107px\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <!-- 2. search 창 -->\r\n");
      out.write("        <section id=\"search_section\">\r\n");
      out.write("            <form class=\"search\">\r\n");
      out.write("                <input type=\"search\" name=\"search\" id=\"searchForm2\" class=\"searchForm\">\r\n");
      out.write("                <button type=\"submit\" id=\"btnSubmit2\" class=\"btnSubmit\">\r\n");
      out.write("                    <img src=\"https://i.ibb.co/ByBFcyt/search.png\" alt=\"search\" width=\"27px\"/>\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <!-- 3. 지역 기업 랭킹 -->\r\n");
      out.write("        <section id=\"com-section3\">\r\n");
      out.write("            <div class=\"com-lank\">\r\n");
      out.write("                <div class=\"com-lank-h\">\r\n");
      out.write("                    <h5>내 지역 기업 랭킹</h5>\r\n");
      out.write("                    <div class=\"more\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/company_review/list.jsp\">+ MORE</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <table class=\"com-lank-list\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>한화생명</td>\r\n");
      out.write("                        <td>보험</td>\r\n");
      out.write("                        <td style=\"font-size:25px; color:#FFC300;\">★★★★★</td>\r\n");
      out.write("                        <td>4.8</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>2</td>\r\n");
      out.write("                        <td>파리바게트 서울역사점</td>\r\n");
      out.write("                        <td>보험</td>\r\n");
      out.write("                        <td style=\"font-size:25px; color:#FFC300;\">★★★★★</td>\r\n");
      out.write("                        <td>4.8</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>3</td>\r\n");
      out.write("                        <td>한화생명</td>\r\n");
      out.write("                        <td>건설 제조 업체</td>\r\n");
      out.write("                        <td style=\"font-size:25px; color:#FFC300;\">★★★★★</td>\r\n");
      out.write("                        <td>4.8</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>4</td>\r\n");
      out.write("                        <td>한화생명</td>\r\n");
      out.write("                        <td>요식업계</td>\r\n");
      out.write("                        <td style=\"font-size:25px; color:#FFC300;\">★★★★★</td>\r\n");
      out.write("                        <td>4.8</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>5</td>\r\n");
      out.write("                        <td>한화생명</td>\r\n");
      out.write("                        <td>보험</td>\r\n");
      out.write("                        <td style=\"font-size:25px; color:#FFC300;\">★★★★★</td>\r\n");
      out.write("                        <td>4.8</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"com-lank\">\r\n");
      out.write("                <div class=\"com-lank-h\">\r\n");
      out.write("                    <h5>전체 지역 기업 랭킹</h5>\r\n");
      out.write("                    <div class=\"more\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/company_review/list.jsp\">+ MORE</a></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <table class=\"com-lank-list\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>한화생명</td>\r\n");
      out.write("                        <td>보험</td>\r\n");
      out.write("                        <td style=\"font-size:25px; color:#FFC300;\">★★★★★</td>\r\n");
      out.write("                        <td>4.8</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>2</td>\r\n");
      out.write("                        <td>파리바게트 서울역사점</td>\r\n");
      out.write("                        <td>보험</td>\r\n");
      out.write("                        <td style=\"font-size:25px; color:#FFC300;\">★★★★★</td>\r\n");
      out.write("                        <td>4.8</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>3</td>\r\n");
      out.write("                        <td>한화생명</td>\r\n");
      out.write("                        <td>건설 제조 업체</td>\r\n");
      out.write("                        <td style=\"font-size:25px; color:#FFC300;\">★★★★★</td>\r\n");
      out.write("                        <td>4.8</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>4</td>\r\n");
      out.write("                        <td>한화생명</td>\r\n");
      out.write("                        <td>요식업계</td>\r\n");
      out.write("                        <td style=\"font-size:25px; color:#FFC300;\">★★★★★</td>\r\n");
      out.write("                        <td>4.8</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>5</td>\r\n");
      out.write("                        <td>한화생명</td>\r\n");
      out.write("                        <td>보험</td>\r\n");
      out.write("                        <td style=\"font-size:25px; color:#FFC300;\">★★★★★</td>\r\n");
      out.write("                        <td>4.8</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <!-- 4. 지역 베스트 리뷰 -->\r\n");
      out.write("        <section id=\"com-section4\">\r\n");
      out.write("            <div class=\"best-review\">\r\n");
      out.write("                <h5>내 지역 베스트 리뷰</h5>\r\n");
      out.write("                <div class=\"best-review-box\">\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <div class=\"best-num\">1</div>\r\n");
      out.write("                        <div class=\"best-review-co\">\r\n");
      out.write("                            파리바게트 상계제일점\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"best-review-txt\">\r\n");
      out.write("                            오늘 이 글을 읽으면서 많은 동기를 받았어요. 감사합니다.오늘 이 글을 읽으면서 많은 동기를 받았어요. 감사합니다.\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"best-review-ni\">\r\n");
      out.write("                            crimsonkycrimsonkycrimsonky\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"best-review-box\" style=\"margin: 0 14.3px;\">\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <div class=\"best-num\">2</div>\r\n");
      out.write("                        <div class=\"best-review-co\">\r\n");
      out.write("                            배달의 민족\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"best-review-txt\">\r\n");
      out.write("                            오늘 이 글을 읽으면서 많은 동기를 받았어요. 감사합니다.\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"best-review-ni\">\r\n");
      out.write("                            crimsonky\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"best-review-box\">\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <div class=\"best-num\">3</div>\r\n");
      out.write("                        <div class=\"best-review-co\">\r\n");
      out.write("                            배달의 민족\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"best-review-txt\">\r\n");
      out.write("                            오늘 이 글을 읽으면서 많은 동기를 받았어요. 감사합니다.\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"best-review-ni\">\r\n");
      out.write("                            crimsonky\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"best-review\">\r\n");
      out.write("                <h5>전체 베스트 리뷰</h5>\r\n");
      out.write("                <div class=\"best-review-box\">\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <div class=\"best-num\">1</div>\r\n");
      out.write("                        <div class=\"best-review-co\">\r\n");
      out.write("                            배달의 민족\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"best-review-txt\">\r\n");
      out.write("                            오늘 이 글을 읽으면서 많은 동기를 받았어요. 감사합니다.\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"best-review-ni\">\r\n");
      out.write("                            crimsonky\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"best-review-box\"  style=\"margin: 0 14.3px;\">\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <div class=\"best-num\">2</div>\r\n");
      out.write("                        <div class=\"best-review-co\">\r\n");
      out.write("                            배달의 민족\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"best-review-txt\">\r\n");
      out.write("                            오늘 이 글을 읽으면서 많은 동기를 받았어요. 감사합니다.\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"best-review-ni\">\r\n");
      out.write("                            crimsonky\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"best-review-box\">\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                        <div class=\"best-num\">3</div>\r\n");
      out.write("                        <div class=\"best-review-co\">\r\n");
      out.write("                            배달의 민족\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"best-review-txt\">\r\n");
      out.write("                            오늘 이 글을 읽으면서 많은 동기를 받았어요. 감사합니다.\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"best-review-ni\">\r\n");
      out.write("                            crimsonky\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <!-- 5. 최근 기업 리뷰 -->\r\n");
      out.write("        <section id=\"com-section5\">\r\n");
      out.write("            <h5>최근 기업 리뷰</h5>\r\n");
      out.write("            <div class=\"fast-re\">\r\n");
      out.write("                <div class=\"fast-re-box\">\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                    <div class=\"fast-re-co\">\r\n");
      out.write("                        하얀풍차제과점 강남역\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fast-re-date\">\r\n");
      out.write("                        2023.12.20\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fast-re-txt\">\r\n");
      out.write("                        오늘 이 글을 읽으면서 많은 동기를 받았어요. 감사합니다.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"fast-re-box2\">\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                    <div class=\"fast-re-co\">\r\n");
      out.write("                        하얀풍차제과점 강남역\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fast-re-date\">\r\n");
      out.write("                        2023.12.20\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fast-re-txt\">\r\n");
      out.write("                        오늘 이 글을 읽으면서 많은 동기를 받았어요. 감사합니다.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"fast-re-box\">\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                    <div class=\"fast-re-co\">\r\n");
      out.write("                        하얀풍차제과점 강남역\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fast-re-date\">\r\n");
      out.write("                        2023.12.20\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fast-re-txt\">\r\n");
      out.write("                        오늘 이 글을 읽으면서 많은 동기를 받았어요. 감사합니다.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"fast-re-box2\">\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                    <div class=\"fast-re-co\">\r\n");
      out.write("                        하얀풍차제과점 강남역\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fast-re-date\">\r\n");
      out.write("                        2023.12.20\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fast-re-txt\">\r\n");
      out.write("                        오늘 이 글을 읽으면서 많은 동기를 받았어요. 감사합니다.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"fast-re-box\">\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                    <div class=\"fast-re-co\">\r\n");
      out.write("                        하얀풍차제과점 강남역\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fast-re-date\">\r\n");
      out.write("                        2023.12.20\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fast-re-txt\">\r\n");
      out.write("                        오늘 이 글을 읽으면서 많은 동기를 받았어요. 감사합니다.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"fast-re-box2\">\r\n");
      out.write("                    <a href=\"\">\r\n");
      out.write("                    <div class=\"fast-re-co\">\r\n");
      out.write("                        하얀풍차제과점 강남역\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fast-re-date\">\r\n");
      out.write("                        2023.12.20\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fast-re-txt\">\r\n");
      out.write("                        오늘 이 글을 읽으면서 많은 동기를 받았어요. 감사합니다.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("	\r\n");
      out.write("    <!-- 푸터 -->\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/common/footer.jsp", out, false);
      out.write(" \r\n");
      out.write("   \r\n");
      out.write("	<!--js 추가-->\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /views/company_review/index.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /views/company_review/index.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/views/company_review/index.jsp(4,0) '${ pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
